<?php

namespace DoctrineORMModule\Proxy\__CG__\Rcm\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Country extends \Rcm\Entity\Country implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function setCountryName($countryName)
    {
        $this->__load();
        return parent::setCountryName($countryName);
    }

    public function getCountryName()
    {
        $this->__load();
        return parent::getCountryName();
    }

    public function setIso2($iso2)
    {
        $this->__load();
        return parent::setIso2($iso2);
    }

    public function getIso2()
    {
        $this->__load();
        return parent::getIso2();
    }

    public function setIso3($iso3)
    {
        $this->__load();
        return parent::setIso3($iso3);
    }

    public function getIso3()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["iso3"];
        }
        $this->__load();
        return parent::getIso3();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'iso3', 'iso2', 'countryName');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields as $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}