CREATE USER 'root'@'%' IDENTIFIED BY 'root';
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' WITH GRANT OPTION;
SET PASSWORD FOR 'root'@'localhost' = PASSWORD('root');
FLUSH privileges;
CREATE DATABASE CMS DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
